### ISSUE TITLE
feat: Add signup and sign-in with EOA 

### ISSUE THREAD

**Issue by dylsteck** [dylsteck/farcaster-kit#4]
### Description

Add components & hooks for signup and sign-in with an EOA. This will be compatible with(and come with examples for) Dynamic, Privy, and RainbowKit out of the box, with future support for embedded wallets to further improve the signup/sign-in UX. 

### Progress 

- Signups are about ~90% done, you can see and read more about this integration's progress [here](https://github.com/dylsteck/farcasterkit/tree/auth/examples/auth/with-privy)
  - Need to fix an error I'm getting when calling the Bundler contract, then I can patch up styling and add the components/hooks to the `farcasterkit` package

**Comment by dylsteck** [comment]
note: two other follow-up features to the auth stack after these are complete would be [Farcaster Connect](https://warpcast.notion.site/Farcaster-Connect-Public-9b3e9fb7a4b74f158369796f3e77c1d3)(account verification only, coming soon from Warpcast) and Warpcast Sign-In(traditional deep-linked sign-in without an EOA)

**Comment by nerypy** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @gtsigner, @xlansmasry, @evertonfraga, @maxmehlbaum, @PolymathWhiz, @xoxokss, @cyrusssschen

**Comment by dylsteck** [comment]
Adding all open issues to my [working branch(auth)'s README](https://github.com/dylsteck/farcasterkit/blob/auth/README.md) for now
